export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_IN_PROGRESS = "USER_LOGIN_IN_PROGRESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const AUTO_AUTHENTICATE_USER_SUCCESS = "AUTO_AUTHENTICATE_USER_SUCCESS";
export const AUTO_AUTHENTICATE_USER_FAILED = "AUTO_AUTHENTICATE_USER_FAILED";
export const AUTO_AUTHENTICATE_USER_IN_PROGRESS =
    "AUTO_AUTHENTICATE_USER_IN_PROGRESS";
export const AUTO_AUTHENTICATE_USER_FAILED_NO_LOCALS =
    "AUTO_AUTHENTICATE_USER_FAILED_NO_LOCALS";

export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";

export const GET_CAMPAIGN_SUCCESS = "GET_CAMPAIGN_SUCCESS";
export const GET_CAMPAIGN_FAILED = "GET_CAMPAIGN_FAILED";
export const GET_CAMPAIGN_IN_PROGRESS = "GET_CAMPAIGN_IN_PROGRESS";

export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAILED = "GET_CATEGORY_LIST_FAILED";
export const GET_CATEGORY_LIST_IN_PROGRESS = "GET_CATEGORY_LIST_IN_PROGRESS";

export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAILED = "UPDATE_CAMPAIGN_FAILED";
export const UPDATE_CAMPAIGN_IN_PROGRESS = "UPDATE_CAMPAIGN_IN_PROGRESS";

export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILED = "UPDATE_COMMENT_FAILED";
export const UPDATE_COMMENT_IN_PROGRESS = "UPDATE_COMMENT_IN_PROGRESS";

export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILED = "CREATE_CAMPAIGN_FAILED";
export const CREATE_CAMPAIGN_IN_PROGRESS = "CREATE_CAMPAIGN_IN_PROGRESS";

export const CREATE_DONATION_SUCCESS = "CREATE_DONATION_SUCCESS";
export const CREATE_DONATION_FAILED = "CREATE_DONATION_FAILED";
export const CREATE_DONATION_IN_PROGRESS = "CREATE_DONATION_IN_PROGRESS";

export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED";
export const CREATE_COMMENT_IN_PROGRESS = "CREATE_COMMENT_IN_PROGRESS";

export const CREATE_LIKE_SUCCESS = "CREATE_LIKE_SUCCESS";
export const CREATE_LIKE_FAILED = "CREATE_LIKE_FAILED";
export const CREATE_LIKE_IN_PROGRESS = "CREATE_LIKE_IN_PROGRESS";

export const CREATE_REPORTING_SUCCESS = "CREATE_REPORTING_SUCCESS";
export const CREATE_REPORTING_FAILED = "CREATE_REPORTING_FAILED";

export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_FAILED = "DELETE_CAMPAIGN_FAILED";
export const DELETE_CAMPAIGN_IN_PROGRESS = "DELETE_CAMPAIGN_IN_PROGRESS";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED";
export const DELETE_COMMENT_IN_PROGRESS = "DELETE_COMMENT_IN_PROGRESS";

export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS";
export const DELETE_LIKE_FAILED = "DELETE_LIKE_FAILED";
export const DELETE_LIKE_IN_PROGRESS = "DELETE_LIKE_IN_PROGRESS";

export const GET_CAMPAIGN_LIST_SUCCESS = "GET_CAMPAIGN_LIST_SUCCESS";
export const GET_CAMPAIGN_LIST_FAILED = "GET_CAMPAIGN_LIST_FAILED";
export const GET_CAMPAIGN_LIST_IN_PROGRESS = "GET_CAMPAIGN_LIST_IN_PROGRESS";

export const GET_DONATION_LIST_SUCCESS = "GET_DONATION_LIST_SUCCESS";
export const GET_DONATION_LIST_FAILED = "GET_DONATION_LIST_FAILED";
export const GET_DONATION_LIST_IN_PROGRESS = "GET_DONATION_LIST_IN_PROGRESS";

export const INITIAL = "INITIAL";

export const CAMPAIGNS_URL = "campaigns";
export const DASHBOARD_URL = "dashboard";
export const PUBLIC_CAMPAIGNS = "public-campaigns";

export const USER_ROLE_DONOR = "DONOR";
export const USER_ROLE_CAMPAIGNER = "CAMPAIGNER";
export const USER_ROLE_ADMIN = "ADMIN";

export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";
export const GET_RATING_FAILED = "GET_RATING_FAILED";

export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILED = "CREATE_RATING_FAILED";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const GET_PROOF_LIST_SUCCESS = "GET_PROOF_LIST_SUCCESS";
export const GET_PROOF_LIST_FAILED = "GET_PROOF_LIST_FAILED";

export const DELETE_PROOF_SUCCESS = "DELETE_PROOF_SUCCESS";
export const DELETE_PROOF_FAILED = "DELETE_PROOF_FAILED";

export const CREATE_PROOF_SUCCESS = "CREATE_PROOF_SUCCESS";
export const CREATE_PROOF_FAILED = "CREATE_PROOF_FAILED";
