export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_IN_PROGRESS = "USER_LOGIN_IN_PROGRESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const AUTO_AUTHENTICATE_USER_SUCCESS = "AUTO_AUTHENTICATE_USER_SUCCESS";
export const AUTO_AUTHENTICATE_USER_FAILED = "AUTO_AUTHENTICATE_USER_FAILED";
export const AUTO_AUTHENTICATE_USER_IN_PROGRESS =
    "AUTO_AUTHENTICATE_USER_IN_PROGRESS";
export const AUTO_AUTHENTICATE_USER_FAILED_NO_LOCALS =
    "AUTO_AUTHENTICATE_USER_FAILED_NO_LOCALS";

export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";

export const GET_CAMPAIGN_SUCCESS = "GET_CAMPAIGN_SUCCESS";
export const GET_CAMPAIGN_FAILED = "GET_CAMPAIGN_FAILED";
export const GET_CAMPAIGN_IN_PROGRESS = "GET_CAMPAIGN_IN_PROGRESS";

export const GET_CATEGORY_LIST_SUCCESS = "GET_CATAUTO_EGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAILED = "GET_CATEGORY_LIST_FAILED";
export const GET_CATEGORY_LIST_IN_PROGRESS = "GET_CATEGORY_LIST_IN_PROGRESS";

export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAILED = "UPDATE_CAMPAIGN_FAILED";
export const UPDATE_CAMPAIGN_IN_PROGRESS = "UPDATE_CAMPAIGN_IN_PROGRESS";

export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILED = "CREATE_CAMPAIGN_FAILED";
export const CREATE_CAMPAIGN_IN_PROGRESS = "CREATE_CAMPAIGN_IN_PROGRESS";

export const GET_CAMPAIGN_LIST_SUCCESS = "GET_CAMPAIGN_LIST_SUCCESS";
export const GET_CAMPAIGN_LIST_FAILED = "GET_CAMPAIGN_LIST_FAILED";
export const GET_CAMPAIGN_LIST_IN_PROGRESS = "GET_CAMPAIGN_LIST_IN_PROGRESS";

export const INITIAL = "INITIAL";

export const CAMPAIGNS_URL = "campaigns";
export const DASHBOARD_URL = "home";
export const PUBLIC_CAMPAIGNS = "public-campaigns";
