export const IN_PROGRESS = "IN_PROGRESS";
export const COMPLETED = "COMPLETED";
export const FAILED = "FAILED";
export const STARTED = "STARTED";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTO_AUTH_SUCCESS = "AUTO_AUTH_SUCCESS";
export const AUTO_AUTH_FAILED = "AUTO_AUTH_FAILED";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const INITIAL = "INITIAL";
export const IN_PROGRESS_STATUS = "IN_PROGRESS_STATUS";
